version: "3.7"
services:
  nginx:
    container_name: nginx
    restart: unless-stopped
    hostname: ${DOMAIN_NAME:?err}
    volumes:
      - './repo:/var/lib/nginx/html/repo/chaotic-aur:ro'
      - './data/acme-webroot:/var/lib/nginx/html/acme:ro'
      - './data/letsencrypt/etc:/etc/letsencrypt:ro'
      - './preset/nginx.conf:/etc/nginx/nginx.conf:ro'
      - './preset/conf.d-tunnels:/etc/nginx/conf.d:ro'
    image: nginx

  syncthing:
    image: linuxserver/syncthing
    container_name: syncthing
    hostname: ${DOMAIN_NAME:?err}
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
        - './data/syncthing:/config'
        - './repo:/repo'
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    restart: unless-stopped

  cloudflared:
    image: cloudflare/cloudflared:2022.2.2
    container_name: cloudflared
    command: tunnel run --url http://nginx ${DOMAIN_NAME:?err}
    user: root
    restart: unless-stopped
    volumes:
      - './data/cloudflared/etc:/etc/cloudflared'
      - './data/cloudflared/home:/root'
